### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by Veilure** [Daxble/TFA-Bullet-Ballistics#4]
Hi, I followed the link from the Steam Workshop page to ask if it would be possible to add a command to reduce the range necessary for the addon to work? Yes, it is a bizarre request since it would be utterly chaotic, what with the bullets going through walls at close range as you had told me, but I'm speaking from the perspective of a primarily single-player kind of person who just adores the amount of chaos he can inflict upon the entirety of his little sandbox. No worries if it's not possible or not an interest to you though~

**Comment by Daxble** [comment]
I will not be adding this, you wouldn't notice a difference because of how fast the bullet are anyways.
