### ISSUE TITLE
Feature Request: Bullet Ricochet

### ISSUE THREAD

**Issue by Erppa112** [Daxble/TFA-Bullet-Ballistics#5]
i think the mod should have the ability to make bullets be able to ricochet off flat hard surfaces like metal, 
but when the bullet ricochets off a surface it should lose velocity and damage, as well there should be a possibility that the bullet won't ricochet (or will fragment but that is not a feature that needs to be added it would just be cool). When firing a shotgun some of the pellets should not ricochet for more realism or it should be randomized that witch of the pellets would be ricocheted

**Comment by Daxble** [comment]
If you enable the default bullet richochets in TFA, it should work fine.
